import React, { useState } from 'react';
import Head from 'next/head';
import Script from 'next/script';
import styled from 'styled-components';

import Gachapon from '../components/Gachapon';
import Winner from '../components/Winner';
import NameList from '../components/NameList'

const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
  height: 100vh;
  width: 100vw;
  background-image: url('/Kdan_background.png');
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Script src="https://kit.fontawesome.com/94b5ea6607.js"></Script>
        <Gachapon />
        <Winner />
        <NameList />
      </Container>
    </>
  )
}
