import React from 'react';
import Head from 'next/head';
import Script from 'next/script';
import styled from 'styled-components';
import { useSelector, useDispatch } from 'react-redux';

import Rocket from '../components/Rocket';
import Winner from '../components/Winner';
import NameList from '../components/NameList'
import Meteors from '../components/Meteors';
import Planet from '../components/Planet';

import {
  setActive, setOpened, setWinnerList, setAllWinnerList, setLotteryList
} from '../slice/mainSlice';

const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
  overflow: hidden;
  height: 100vh;
  width: 100vw;
  background-image: url('/background.png');
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
`
const color = '#ff0000';
const color_dark = `#7b0000`;
const color_border = `#ff3030`;
const color_text = `#fff`;

const GoButton = styled.button`
  background: ${color};
  border-radius: 3em;
  border: 0;
  border: 3px solid ${color_border};
  color: ${color_text};
  cursor: pointer;
  font-weight: bold;
  outline: none;
  padding: 1.25em 3em;
  text-transform: uppercase;
  transform-style: preserve-3d;
  transition: all 150ms cubic-bezier(.175, .885, .32, 1.275);
  font-size: 18px;

  z-index: 40;
  top: 24px;
  left: calc(50% - 86px);
  position: absolute;
  
  &::before {
    background: ${color_dark};
    border-radius: inherit;
    box-shadow:
      0 0 0 2px ${color_border},
      0 .6em 0 0 rgba(${color}, .6);
    content: '';
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    transform: translate3d(0, .75em, -1em);
    transition: all 150ms cubic-bezier(.175, .885, .32, 1.275);
    width: 100%;
  }

  &:active {
    background: ${color};
    transform: translate(0, .75em);

    &::before {
      box-shadow:
        0 0 0 3px ${color_border},
        0 0 ${color};
      transform: translate3d(0, 0, -1em);
    }
  }
`;

const Wrapper = styled.div`
  position: absolute;
  bottom: -108px;
  z-index: 25;
`;

const ButtonBG = styled.div`
  width: 240px;
  height: 240px;
  display: block;
  background-color: #050f48;
  border-radius: 20px;
  left: calc(50% - 160px);
`;

export default function Home() {
  const dispatch = useDispatch();
  const { isActive, lotteryList, allWinnerList, pickOutCount } = useSelector((state) => state.main);

  const handleClick = () => {
    if (!isActive) {
      dispatch(setActive(true));
      const restList = [...lotteryList];

      if (lotteryList.length >= 1) {
        const winners = [];

        for (let index = 0; index < pickOutCount; index++) {
          if (restList.length) {
            const luckyNum = Math.floor(Math.random() * restList.length);
            winners.push(restList[luckyNum]);
            restList.splice(luckyNum, 1);
          }
        }

        dispatch(setLotteryList(restList));
        dispatch(setWinnerList(winners));
        dispatch(setAllWinnerList([...allWinnerList].concat(winners)));
      } else {
        dispatch(setWinnerList([ "抽完惹" ]));
      }

      setTimeout(() => {
        dispatch(setActive(false))
        dispatch(setOpened(true))
      }, 2200);
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Script src="https://kit.fontawesome.com/94b5ea6607.js"></Script>
        <Wrapper>
          <GoButton onClick={handleClick}>START</GoButton>
          <ButtonBG />
        </Wrapper>
        <Meteors />
        <Planet />
        <Rocket />
        <Winner />
        <NameList />
      </Container>
    </>
  )
}
